version: '3'
services:
  postgres:
    image: postgres:9.6.5
    ports:
      - '5432:5432'
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 'admin'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - 'postgres'
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
