version: '3'
services:
  postgres:
    image: postgres:9.6.5
    ports:
      - '5432:5432'
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 'admin'
  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - '5050:5050'
    depends_on:
      - 'postgres'
    hostname: pgadmin
    container_name: pgadmin
    environment:
      DEFAULT_USER: 'pgadmin4@pgadmin.org'
      DEFAULT_PASSWORD: 'admin'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  pgadmin2:
    image: dpage/pgadmin4
    ports:
      - '5050:5051'
    depends_on:
      - 'postgres'
    hostname: pgadmin
    container_name: pgadmin2
    environment:
      DEFAULT_USER: 'pgadmin4@pgadmin.org'
      DEFAULT_PASSWORD: 'admin'
