spring:
  cloud:
    gcp:
      project-id: egoetschalckx-test
    pubsub:
      emulatorHost: localhost:8085
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloudpush
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

logging:
  level:
    org.springframework: info
    org:
      springframework:
        cloud:
          gcp:
            pubsub:
              core:
                publisher: debug